<a href="https://colab.research.google.com/github/FernandoBRdgz/diplomado_ds_mod4/blob/main/4.1%20Introducci%C3%B3n%20a%20Redes%20Neuronales%20Artificiales/4.1.1%20Vectorizaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Broadcasting

Los arreglos de numpy se diferencian de las listas normales de Python debido a su capacidad para hacer broadcasting. Con las listas, solo puede operar con objetos del mismo tamaño y forma. Es decir, si se quisiera reemplazar los primeros 5 elementos de una lista con un nuevo valor, tendría que iterar sobre los 5 elementos de la lista. Con los arreglos de numpy, puede "transmitir" un solo valor a través de un conjunto más grande de valores.

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

La siguiente celda generará un *Warning* sobre la división por cero, ¡pero no un arrojará *Error*! Simplemente llena la posición con *nan*.

In [ ]:
arr / arr

<ipython-input-32-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1 / arr

<ipython-input-33-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

#### Funciones Universales

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-38-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

#### Funciones Estadísticas

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

In [ ]:
arr.min()

0

In [ ]:
arr.var()

8.25

In [ ]:
arr.std()

2.8722813232690143

### Vectorización

La vectorización es un método para lograr el paralelismo dentro de un solo núcleo de procesador.

Para expresarlo en términos sencillos, una sola instrucción se realiza sobre cada elemento individual de una matriz en un solo núcleo de CPU de manera paralela. La operación vectorizada puede reemplazar los bucles *for* tradicionales , ejecutarse más rápido, trabajar en diferentes tamaños de dimensión de matriz. Es una solución matricial que reemplaza explícitamente el bucle *for*.

In [ ]:
import time
import numpy as np

In [ ]:
size = 100000

In [ ]:
np.random.seed(0)
vec_1 = np.random.random(size)
vec_2 = np.random.random(size)

In [ ]:
# SIN Vectorización

tic = time.process_time()

python_product = np.zeros((size, size))

for i in range(size):
    for j in range(size):
        python_product[i][j] = vec_1[i] * vec_2[j]

phyton_time = time.process_time() - tic
print('Tiempo de Python', phyton_time)

Tiempo de Python 42.84706878


In [ ]:
# CON Vectorización

tic = time.process_time()
numpy_product = np.outer(vec_1, vec_2)

numpy_time = time.process_time() - tic
print('Tiempo de Numpy', numpy_time)

Tiempo de Numpy 0.09762745399999062


In [ ]:
np.sum(python_product != numpy_product)

0

In [ ]:
print('Mejora con Numpy', phyton_time / numpy_time)

Mejora con Numpy 438.88339831134095
